## Importing libraries

In [60]:
import pandas as pd
import requests
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor


from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.exceptions import NotFittedError
import requests

In [61]:
df1 = pd.read_csv('../csv files/india 2021-01-01 to 2022-04-18.csv')
pd.set_option('display.max_rows', None) 
pd.set_option('display.max_columns', None)
df1.head()

name    datetime  tempmax  tempmin  temp  feelslikemax  feelslikemin  \
0  india  2021-01-01     18.1      3.7  10.1          18.1           3.7   
1  india  2021-01-02     19.0      7.7  13.4          19.0           7.7   
2  india  2021-01-03     17.0     11.1  13.9          17.0          11.1   
3  india  2021-01-04     21.7     12.2  16.2          21.7          12.2   
4  india  2021-01-05     20.7     14.5  17.1          20.7          14.5   

   feelslike   dew  humidity  precip  precipprob  precipcover preciptype  \
0       10.1   6.1     79.01     0.0         NaN         0.00        NaN   
1       13.4   9.3     77.86     1.0         NaN         4.17        NaN   
2       13.9  12.2     90.10    39.0         NaN        12.50        NaN   
3       16.2  15.2     94.23     5.0         NaN         8.33        NaN   
4       17.1  16.0     93.84     0.1         NaN         4.17        NaN   

   snow  snowdepth  windgust  windspeed  winddir  sealevelpressure  \
0   NaN        NaN       NaN       11.2     69.4            1018.5   
1   NaN        NaN       NaN       16.6     83.8            1016.7   
2   NaN        NaN       NaN       16.6     75.5            1015.1   
3   NaN        NaN       NaN       18.4    136.1            1016.2   
4   NaN        NaN       NaN       14.8    106.1            1015.6   

   cloudcover  visibility  solarradiation  solarenergy  uvindex  severerisk  \
0         6.6         0.7             NaN          NaN      NaN         NaN   
1        71.0         1.2             NaN          NaN      NaN         NaN   
2        80.2         1.1             NaN          NaN      NaN         NaN   
3        70.7         0.8             NaN          NaN      NaN         NaN   
4        85.6         1.7             NaN          NaN      NaN         NaN   

               sunrise               sunset  moonphase  \
0  2021-01-01T07:14:04  2021-01-01T17:35:29       0.53   
1  2021-01-02T07:14:19  2021-01-02T17:36:11       0.56   
2  2021-01-03T07:14:32  2021-01-03T17:36:53       0.60   
3  2021-01-04T07:14:43  2021-01-04T17:37:37       0.65   
4  2021-01-05T07:14:53  2021-01-05T17:38:22       0.70   

               conditions                                        description  \
0                   Clear               Clear conditions throughout the day.   
1  Rain, Partially cloudy  Partly cloudy throughout the day with morning ...   
2  Rain, Partially cloudy  Partly cloudy throughout the day with rain in ...   
3  Rain, Partially cloudy        Partly cloudy throughout the day with rain.   
4  Rain, Partially cloudy  Partly cloudy throughout the day with morning ...   

   icon                                           stations  
0   fog  42182099999,42176099999,VIDP,42139099999,42181...  
1  rain  42182099999,42176099999,VIDP,42139099999,42181...  
2  rain  42182099999,42176099999,VIDP,42139099999,42181...  
3  rain  42182099999,42176099999,VIDP,42139099999,42181...  
4  rain  42182099999,42176099999,VIDP,42139099999,42181...

In [62]:
df2 = pd.read_csv('../csv files/germany.csv')
df2.head()

name    datetime  tempmax  tempmin  temp  feelslikemax  feelslikemin  \
0  germany  2022-04-19     11.8      4.0   8.2          11.8           0.0   
1  germany  2022-04-20     14.5      3.6   8.6          14.5           2.0   
2  germany  2022-04-21     13.5      4.3   8.4          13.5           2.1   
3  germany  2022-04-22     15.1      4.7   9.3          15.1           2.6   
4  germany  2022-04-23     14.9      5.1   9.8          14.9           3.0   

   feelslike  dew  humidity  precip  precipprob  precipcover preciptype  snow  \
0        7.0 -1.6      51.2     0.0         4.8          NaN       rain     0   
1        8.0  2.4      67.3     0.0         9.5          NaN       rain     0   
2        7.2  4.2      76.1     0.2        14.3          NaN       rain     0   
3        8.4  3.7      70.6     0.4         0.0          NaN       rain     0   
4        8.5  4.0      68.5     0.0         4.8          NaN        NaN     0   

   snowdepth  windgust  windspeed  winddir  sealevelpressure  cloudcover  \
0          0      48.2       20.2     52.4            1015.8        61.4   
1          0      36.0       15.1    151.5            1018.3        91.7   
2          0      31.3       13.0    157.4            1014.0        81.4   
3          0      43.9       18.7     59.0            1010.0        62.6   
4          0      42.5       24.1     54.9            1011.0        39.7   

   visibility  solarradiation  solarenergy  uvindex  severerisk  \
0        18.8           201.7         17.6        8          10   
1        24.1            67.0          5.8        3          10   
2        23.8            15.0          1.3        0          10   
3        24.1            41.3          3.5        1          10   
4        24.1           210.5         18.3        6          10   

               sunrise               sunset  moonphase        conditions  \
0  2022-04-19T06:00:17  2022-04-19T20:12:11       0.55  Partially cloudy   
1  2022-04-20T05:58:07  2022-04-20T20:13:55       0.59          Overcast   
2  2022-04-21T05:55:58  2022-04-21T20:15:40       0.64  Partially cloudy   
3  2022-04-22T05:53:50  2022-04-22T20:17:24       0.70  Partially cloudy   
4  2022-04-23T05:51:43  2022-04-23T20:19:09       0.75  Partially cloudy   

                         description               icon    stations  
0  Partly cloudy throughout the day.  partly-cloudy-day  EDDB,E2835  
1   Cloudy skies throughout the day.             cloudy         NaN  
2  Partly cloudy throughout the day.  partly-cloudy-day         NaN  
3  Partly cloudy throughout the day.  partly-cloudy-day         NaN  
4  Partly cloudy throughout the day.  partly-cloudy-day         NaN

In [63]:
final_df = pd.concat([df1, df2], axis=0,ignore_index= True)
final_df

name    datetime  tempmax  tempmin  temp  feelslikemax  feelslikemin  \
0      india  2021-01-01     18.1      3.7  10.1          18.1           3.7   
1      india  2021-01-02     19.0      7.7  13.4          19.0           7.7   
2      india  2021-01-03     17.0     11.1  13.9          17.0          11.1   
3      india  2021-01-04     21.7     12.2  16.2          21.7          12.2   
4      india  2021-01-05     20.7     14.5  17.1          20.7          14.5   
5      india  2021-01-06     20.3     15.0  16.5          20.3          15.0   
6      india  2021-01-07     19.4     12.5  16.3          19.4          12.5   
7      india  2021-01-08     16.4     11.4  13.5          16.4          11.4   
8      india  2021-01-09     19.4     11.0  14.6          19.4          11.0   
9      india  2021-01-10     15.3      9.0  11.4          15.3           6.7   
10     india  2021-01-11     16.6      7.0  11.3          16.6           5.2   
11     india  2021-01-12     16.0      6.1  10.2          16.0           6.1   
12     india  2021-01-13     16.2      4.9  10.8          16.2           4.9   
13     india  2021-01-14     19.0      4.4  11.2          19.0           4.4   
14     india  2021-01-15     21.0      7.7  12.9          21.0           7.7   
15     india  2021-01-16     17.0      8.0  10.7          17.0           6.8   
16     india  2021-01-17     14.1      6.0  10.3          14.1           4.4   
17     india  2021-01-18     19.2     10.0  13.7          19.2          10.0   
18     india  2021-01-19     19.8      8.9  13.2          19.8           8.9   
19     india  2021-01-20     17.0      9.0  12.4          17.0           6.7   
20     india  2021-01-21     23.0      9.8  14.9          23.0           8.9   
21     india  2021-01-22     17.8      5.8  11.8          17.8           4.2   
22     india  2021-01-23     19.7      9.0  13.2          19.7           7.0   
23     india  2021-01-24     15.0      9.3  12.3          15.0           8.3   
24     india  2021-01-25     17.0      8.6  12.0          17.0           7.6   
25     india  2021-01-26     19.7      6.6  12.6          19.7           6.6   
26     india  2021-01-27     20.5      7.3  12.9          20.5           6.7   
27     india  2021-01-28     19.0      6.0  12.3          19.0           6.0   
28     india  2021-01-29     19.9      6.1  12.3          19.9           6.1   
29     india  2021-01-30     20.8      6.0  12.5          20.8           5.1   
30     india  2021-01-31     22.9      5.5  13.2          22.9           5.5   
31     india  2021-02-01     25.6      7.7  16.4          25.6           7.7   
32     india  2021-02-02     26.1      9.0  17.1          26.1           9.0   
33     india  2021-02-03     25.6     11.9  18.1          25.6          11.9   
34     india  2021-02-04     21.9     12.3  16.5          21.9          12.3   
35     india  2021-02-05     21.0      9.0  14.3          21.0           9.0   
36     india  2021-02-06     22.0      9.4  15.0          22.0           9.1   
37     india  2021-02-07     22.8      9.0  15.1          22.8           8.5   
38     india  2021-02-08     23.7      9.8  15.6          23.7           9.1   
39     india  2021-02-09     25.0     10.0  16.3          25.0          10.0   
40     india  2021-02-10     28.3     11.9  18.4          27.9          11.9   
41     india  2021-02-11     24.0     11.0  16.9          24.0          11.0   
42     india  2021-02-12     26.3     12.0  18.1          26.3          12.0   
43     india  2021-02-13     26.7     14.0  18.4          26.7          14.0   
44     india  2021-02-14     27.8     11.2  18.7          27.8          11.2   
45     india  2021-02-15     28.7     11.3  19.8          29.1          11.3   
46     india  2021-02-16     28.8     13.2  20.6          29.2          13.2   
47     india  2021-02-17     26.8     12.2  18.9          27.0          12.2   
48     india  2021-02-18     27.7     11.3  19.2          28.0          11.3   
49     i

In [64]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 488 entries, 0 to 487
Data columns (total 33 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   name              488 non-null    object 
 1   datetime          488 non-null    object 
 2   tempmax           488 non-null    float64
 3   tempmin           488 non-null    float64
 4   temp              488 non-null    float64
 5   feelslikemax      488 non-null    float64
 6   feelslikemin      488 non-null    float64
 7   feelslike         488 non-null    float64
 8   dew               488 non-null    float64
 9   humidity          488 non-null    float64
 10  precip            488 non-null    float64
 11  precipprob        114 non-null    float64
 12  precipcover       374 non-null    float64
 13  preciptype        21 non-null     object 
 14  snow              114 non-null    float64
 15  snowdepth         114 non-null    float64
 16  windgust          214 non-null    float64
 1

In [65]:
final_df = final_df.drop(['name','datetime','stations','description','sunrise','sunset'],axis = 1)

In [66]:
final_df= final_df.rename(columns={"sealevelpressure": "pressure"})

In [67]:
final_df

tempmax  tempmin  temp  feelslikemax  feelslikemin  feelslike   dew  \
0       18.1      3.7  10.1          18.1           3.7       10.1   6.1   
1       19.0      7.7  13.4          19.0           7.7       13.4   9.3   
2       17.0     11.1  13.9          17.0          11.1       13.9  12.2   
3       21.7     12.2  16.2          21.7          12.2       16.2  15.2   
4       20.7     14.5  17.1          20.7          14.5       17.1  16.0   
5       20.3     15.0  16.5          20.3          15.0       16.5  15.7   
6       19.4     12.5  16.3          19.4          12.5       16.3  14.7   
7       16.4     11.4  13.5          16.4          11.4       13.5  12.2   
8       19.4     11.0  14.6          19.4          11.0       14.6  13.0   
9       15.3      9.0  11.4          15.3           6.7       10.8   9.1   
10      16.6      7.0  11.3          16.6           5.2       10.7   8.8   
11      16.0      6.1  10.2          16.0           6.1       10.1   8.0   
12      16.2      4.9  10.8          16.2           4.9       10.8   7.7   
13      19.0      4.4  11.2          19.0           4.4       11.2   8.2   
14      21.0      7.7  12.9          21.0           7.7       12.9  10.3   
15      17.0      8.0  10.7          17.0           6.8       10.5   9.2   
16      14.1      6.0  10.3          14.1           4.4        9.9   8.7   
17      19.2     10.0  13.7          19.2          10.0       13.7  11.7   
18      19.8      8.9  13.2          19.8           8.9       13.2  11.2   
19      17.0      9.0  12.4          17.0           6.7       11.7  10.1   
20      23.0      9.8  14.9          23.0           8.9       14.8   9.1   
21      17.8      5.8  11.8          17.8           4.2       11.5   9.6   
22      19.7      9.0  13.2          19.7           7.0       12.8  10.3   
23      15.0      9.3  12.3          15.0           8.3       12.2  11.1   
24      17.0      8.6  12.0          17.0           7.6       11.6  10.1   
25      19.7      6.6  12.6          19.7           6.6       12.6   8.0   
26      20.5      7.3  12.9          20.5           6.7       12.7   8.0   
27      19.0      6.0  12.3          19.0           6.0       12.3   7.4   
28      19.9      6.1  12.3          19.9           6.1       12.3   8.0   
29      20.8      6.0  12.5          20.8           5.1       12.2   7.1   
30      22.9      5.5  13.2          22.9           5.5       13.2   6.3   
31      25.6      7.7  16.4          25.6           7.7       16.4   7.7   
32      26.1      9.0  17.1          26.1           9.0       17.1  10.4   
33      25.6     11.9  18.1          25.6          11.9       18.2  13.3   
34      21.9     12.3  16.5          21.9          12.3       16.5  14.3   
35      21.0      9.0  14.3          21.0           9.0       14.3  10.6   
36      22.0      9.4  15.0          22.0           9.1       15.0  11.2   
37      22.8      9.0  15.1          22.8           8.5       15.0  11.6   
38      23.7      9.8  15.6          23.7           9.1       15.6  11.4   
39      25.0     10.0  16.3          25.0          10.0       16.3  11.2   
40      28.3     11.9  18.4          27.9          11.9       18.4  12.4   
41      24.0     11.0  16.9          24.0          11.0       16.9  13.2   
42      26.3     12.0  18.1          26.3          12.0       18.1  14.0   
43      26.7     14.0  18.4          26.7          14.0       18.4  14.1   
44      27.8     11.2  18.7          27.8          11.2       18.7  13.4   
45      28.7     11.3  19.8          29.1          11.3       19.8  14.4   
46      28.8     13.2  20.6          29.2          13.2       20.7  15.4   
47      26.8     12.2  18.9          27.0          12.2       18.9  13.4   
48      27.7     11.3  19.2          28.0          11.3       19.2  13.7   
49      25.7     11.2  18.1          25.7          11.2       18.1  13.6   
50      26.5     12.0  18.2          26.5          12.0       18.2  13.2   
51      27.7     11.8  18.5          28.0          11

In [68]:
final_df['precipprob'].unique()

array([  nan,   0. , 100. ,   4.8,   9.5,  14.3,  23.8,  28.6,  19. ])

In [69]:
final_df.isnull().sum()

tempmax             0
tempmin             0
temp                0
feelslikemax        0
feelslikemin        0
feelslike           0
dew                 0
humidity            0
precip              0
precipprob        374
precipcover       114
preciptype        467
snow              374
snowdepth         374
windgust          274
windspeed           0
winddir             0
pressure            0
cloudcover          0
visibility          0
solarradiation    374
solarenergy       374
uvindex           374
severerisk        374
moonphase           0
conditions          0
icon                0
dtype: int64

In [70]:
final_df['preciptype'].unique()

array([nan, 'rain'], dtype=object)

In [71]:
final_df= final_df.fillna(0)

In [72]:
final_df.isnull().sum()

tempmax           0
tempmin           0
temp              0
feelslikemax      0
feelslikemin      0
feelslike         0
dew               0
humidity          0
precip            0
precipprob        0
precipcover       0
preciptype        0
snow              0
snowdepth         0
windgust          0
windspeed         0
winddir           0
pressure          0
cloudcover        0
visibility        0
solarradiation    0
solarenergy       0
uvindex           0
severerisk        0
moonphase         0
conditions        0
icon              0
dtype: int64

In [73]:
cat_fea = final_df.select_dtypes(include= 'object')
cat_fea


preciptype              conditions               icon
0            0                   Clear                fog
1            0  Rain, Partially cloudy               rain
2            0  Rain, Partially cloudy               rain
3            0  Rain, Partially cloudy               rain
4            0  Rain, Partially cloudy               rain
5            0  Rain, Partially cloudy               rain
6            0        Partially cloudy  partly-cloudy-day
7            0        Partially cloudy  partly-cloudy-day
8            0        Partially cloudy  partly-cloudy-day
9            0        Partially cloudy  partly-cloudy-day
10           0                   Clear          clear-day
11           0                   Clear          clear-day
12           0                   Clear          clear-day
13           0        Partially cloudy                fog
14           0        Partially cloudy                fog
15           0        Partially cloudy                fog
16           0                   Clear                fog
17           0        Partially cloudy  partly-cloudy-day
18           0        Partially cloudy                fog
19           0        Partially cloudy                fog
20           0                   Clear          clear-day
21           0                   Clear          clear-day
22           0        Partially cloudy                fog
23           0        Partially cloudy                fog
24           0                   Clear          clear-day
25           0                   Clear          clear-day
26           0                   Clear          clear-day
27           0                   Clear          clear-day
28           0                   Clear          clear-day
29           0                   Clear          clear-day
30           0                   Clear          clear-day
31           0                   Clear          clear-day
32           0                   Clear          clear-day
33           0        Partially cloudy  partly-cloudy-day
34           0  Rain, Partially cloudy               rain
35           0                   Clear          clear-day
36           0                   Clear          clear-day
37           0                   Clear          clear-day
38           0                   Clear          clear-day
39           0        Partially cloudy  partly-cloudy-day
40           0                   Clear          clear-day
41           0                   Clear          clear-day
42           0        Partially cloudy                fog
43           0        Partially cloudy  partly-cloudy-day
44           0                   Clear          clear-day
45           0                   Clear          clear-day
46           0                   Clear          clear-day
47           0                   Clear          clear-day
48           0                   Clear          clear-day
49           0                   Clear          clear-day
50           0        Partially cloudy  partly-cloudy-day
51           0                   Clear          clear-day
52           0                   Clear          clear-day
53           0                   Clear          clear-day
54           0                   Clear          clear-day
55           0                   Clear          clear-day
56           0                   Clear          clear-day
57           0                   Clear          clear-day
58           0                   Clear          clear-day
59           0                   Clear          clear-day
60           0                   Clear          clear-day
61           0                   Clear          clear-day
62           0                   Clear          clear-day
63           0                   Clear          clear-day
64           0                   Clear          clear-day
65           0                   Clear          clear-day
66           0        Partially cloudy  partly-cloudy-day
67           0  Rain, Partially cloudy               rain
68

In [74]:
final_df.describe()

tempmax     tempmin        temp  feelslikemax  feelslikemin  \
count  488.000000  488.000000  488.000000    488.000000    488.000000   
mean    29.722746   18.212910   23.601434     32.020492     18.790369   
std      7.739883    7.582132    7.558026     10.155845      8.961832   
min      9.200000    2.800000    7.100000      6.500000      0.000000   
25%     23.800000   11.675000   17.350000     23.800000     11.675000   
50%     31.750000   19.050000   25.450000     32.550000     19.050000   
75%     35.800000   25.025000   30.025000     40.700000     25.025000   
max     43.000000   31.700000   37.700000     52.000000     38.800000   

        feelslike         dew    humidity      precip  precipprob  \
count  488.000000  488.000000  488.000000  488.000000  488.000000   
mean    25.027869   15.281557   66.317090    3.644262    2.732172   
std      9.453956    6.907639   19.471164   16.494174   15.100556   
min      4.600000   -1.600000   21.100000    0.000000    0.000000   
25%     17.375000   10.175000   55.777500    0.000000    0.000000   
50%     25.550000   13.650000   69.265000    0.000000    0.000000   
75%     32.325000   21.225000   80.610000    0.000000    0.000000   
max     44.500000   27.800000   99.290000  174.000000  100.000000   

       precipcover   snow  snowdepth    windgust   windspeed     winddir  \
count   488.000000  488.0      488.0  488.000000  488.000000  488.000000   
mean      1.127316    0.0        0.0   14.085041   16.255738  157.172541   
std       3.177809    0.0        0.0   17.708151    5.410554   59.246408   
min       0.000000    0.0        0.0    0.000000    5.400000   41.500000   
25%       0.000000    0.0        0.0    0.000000   13.000000  111.475000   
50%       0.000000    0.0        0.0    0.000000   15.600000  148.300000   
75%       0.000000    0.0        0.0   33.500000   18.400000  199.225000   
max      20.830000    0.0        0.0   79.600000   43.200000  292.300000   

          pressure  cloudcover  visibility  solarradiation  solarenergy  \
count   488.000000  488.000000  488.000000      488.000000    488.00000   
mean   1009.632787   34.361680    3.279303       48.416393      3.88627   
std       6.354981   30.641561    3.775584       93.264237      7.66279   
min     994.700000    0.000000    0.500000        0.000000      0.00000   
25%    1004.675000    1.475000    1.900000        0.000000      0.00000   
50%    1009.700000   30.900000    2.900000        0.000000      0.00000   
75%    1015.000000   59.550000    3.400000        0.000000      0.00000   
max    1023.500000   99.700000   24.100000      302.000000     25.90000   

          uvindex  severerisk   moonphase  
count  488.000000  488.000000  488.000000  
mean     1.717213    2.336066    0.502398  
std      3.272992    4.235589    0.310309  
min      0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.247500  
50%      0.000000    0.000000    0.500000  
75%      0.000000    0.000000    0.760000  
max     10.000000   10.000000    1.000000

In [75]:
final_df['precipcover'].unique()

array([ 0.  ,  4.17, 12.5 ,  8.33,  4.55,  5.  , 16.67,  8.7 , 20.83,
        9.52,  4.35, 17.39])

In [76]:
cat_fea['preciptype'].unique()

array([0, 'rain'], dtype=object)

In [77]:
cat_fea['conditions'].unique()

array(['Clear', 'Rain, Partially cloudy', 'Partially cloudy',
       'Rain, Overcast', 'Rain', 'Overcast'], dtype=object)

In [78]:
cat_fea['icon'].unique()

array(['fog', 'rain', 'partly-cloudy-day', 'clear-day', 'wind', 'cloudy'],
      dtype=object)

In [79]:
le = LabelEncoder()

In [80]:
x= final_df.drop('temp',axis = 1)
y=final_df['temp']

In [81]:
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [82]:
x_train

tempmax  tempmin  feelslikemax  feelslikemin  feelslike   dew  humidity  \
250     32.4     27.0          42.3          31.8       36.2  26.3     84.32   
280     34.9     24.6          37.0          24.6       30.0  21.2     66.97   
323     25.8     15.6          25.8          15.6       19.8  11.4     63.40   
271     34.4     27.0          43.8          31.2       37.3  26.0     79.57   
284     35.9     23.8          36.5          23.8       29.2  19.0     60.29   
291     30.6     20.9          33.0          20.9       25.6  21.3     82.37   
347     21.9      9.7          21.9           9.7       15.1  10.5     77.40   
22      19.7      9.0          19.7           7.0       12.8  10.3     84.08   
236     36.0     29.0          46.3          36.4       40.6  25.9     70.53   
68      32.7     19.3          33.9          19.3       25.5  16.7     60.95   
462     42.0     21.9          38.6          21.9       30.6   5.4     23.10   
154     38.6     23.0          42.3          23.0       33.8  21.5     60.89   
69      34.7     18.2          35.8          18.2       26.1  17.3     63.58   
418     23.8     15.0          23.8          15.0       19.2  15.1     78.20   
121     38.8     26.7          38.8          27.2       31.1  12.0     30.59   
407     22.8      9.8          22.8           8.6       15.9   8.6     66.70   
120     40.7     29.3          41.0          29.0       33.1  11.8     27.34   
483     13.9      3.6          13.9           1.4        8.1   4.0     71.50   
224     35.9     28.0          48.7          32.7       39.7  25.2     67.80   
176     38.0     27.0          42.6          30.0       35.1  22.2     60.33   
170     34.0     26.8          40.7          30.0       34.7  24.9     77.75   
361     17.0     10.9          17.0          10.9       14.2  12.3     88.76   
90      34.0     19.0          31.6          19.0       26.1   3.1     22.60   
159     41.5     31.0          47.4          33.0       41.3  21.1     40.77   
469     40.0     25.4          37.1          25.4       31.1   9.5     27.30   
178     39.3     29.4          45.2          35.5       40.4  23.2     54.22   
375     17.0      8.0          17.0           6.8       11.2   9.9     91.40   
297     28.0     17.4          28.6          17.4       22.4  18.0     78.75   
64      31.0     16.0          30.4          16.0       22.8  14.0     60.35   
0       18.1      3.7          18.1           3.7       10.1   6.1     79.01   
363     18.4      6.1          18.4           6.1       11.9   5.4     70.07   
192     36.7     28.4          45.3          33.9       39.9  26.0     72.73   
366     19.8      7.4          19.8           6.8       12.8   9.0     80.23   
419     25.8     13.5          25.8          13.5       19.6  13.5     72.00   
435     30.7     16.0          29.6          16.0       22.9  13.6     58.90   
147     38.0     26.8          43.0          28.6       34.9  20.3     50.61   
54      31.8     13.2          31.5          13.2       21.6  13.7     65.44   
343     23.0     11.4          23.0          11.4       16.3  11.0     73.67   
48      27.7     11.3          28.0          11.3       19.2  13.7     73.76   
457     39.0     21.3          36.1          21.3       28.9   5.2     26.20   
131     37.0     24.8          36.6          24.8       30.9  15.1     39.88   
330     26.1     12.1          26.1          12.1       18.0  13.3     76.76   
368     22.5      9.7          22.5           9.7       15.8   9.2     71.11   
229     37.6     29.0          44.9          36.7       40.9  25.3     65.95   
402     25.7     10.3          25.7          10.3       17.4  11.6     72.10   
349     19.7     10.4          19.7          10.4       14.6   8.9     70.97   
73      31.7     17.0          31.4          17.0       24.3  15.4     60.61   
36      22.0      9.4          22.0           9.1       15.0  11.2     80.20   
213     32.0     27.0          44.2          31.2       36.5  27.2     91.45   
38   

In [83]:
x_train['preciptype'] = le.fit_transform(x_train['preciptype'].astype(str))
x_train['conditions'] = le.fit_transform(x_train['conditions'].astype(str))
x_train['icon'] = le.fit_transform(x_train['icon'].astype(str))

In [84]:
x_train

tempmax  tempmin  feelslikemax  feelslikemin  feelslike   dew  humidity  \
250     32.4     27.0          42.3          31.8       36.2  26.3     84.32   
280     34.9     24.6          37.0          24.6       30.0  21.2     66.97   
323     25.8     15.6          25.8          15.6       19.8  11.4     63.40   
271     34.4     27.0          43.8          31.2       37.3  26.0     79.57   
284     35.9     23.8          36.5          23.8       29.2  19.0     60.29   
291     30.6     20.9          33.0          20.9       25.6  21.3     82.37   
347     21.9      9.7          21.9           9.7       15.1  10.5     77.40   
22      19.7      9.0          19.7           7.0       12.8  10.3     84.08   
236     36.0     29.0          46.3          36.4       40.6  25.9     70.53   
68      32.7     19.3          33.9          19.3       25.5  16.7     60.95   
462     42.0     21.9          38.6          21.9       30.6   5.4     23.10   
154     38.6     23.0          42.3          23.0       33.8  21.5     60.89   
69      34.7     18.2          35.8          18.2       26.1  17.3     63.58   
418     23.8     15.0          23.8          15.0       19.2  15.1     78.20   
121     38.8     26.7          38.8          27.2       31.1  12.0     30.59   
407     22.8      9.8          22.8           8.6       15.9   8.6     66.70   
120     40.7     29.3          41.0          29.0       33.1  11.8     27.34   
483     13.9      3.6          13.9           1.4        8.1   4.0     71.50   
224     35.9     28.0          48.7          32.7       39.7  25.2     67.80   
176     38.0     27.0          42.6          30.0       35.1  22.2     60.33   
170     34.0     26.8          40.7          30.0       34.7  24.9     77.75   
361     17.0     10.9          17.0          10.9       14.2  12.3     88.76   
90      34.0     19.0          31.6          19.0       26.1   3.1     22.60   
159     41.5     31.0          47.4          33.0       41.3  21.1     40.77   
469     40.0     25.4          37.1          25.4       31.1   9.5     27.30   
178     39.3     29.4          45.2          35.5       40.4  23.2     54.22   
375     17.0      8.0          17.0           6.8       11.2   9.9     91.40   
297     28.0     17.4          28.6          17.4       22.4  18.0     78.75   
64      31.0     16.0          30.4          16.0       22.8  14.0     60.35   
0       18.1      3.7          18.1           3.7       10.1   6.1     79.01   
363     18.4      6.1          18.4           6.1       11.9   5.4     70.07   
192     36.7     28.4          45.3          33.9       39.9  26.0     72.73   
366     19.8      7.4          19.8           6.8       12.8   9.0     80.23   
419     25.8     13.5          25.8          13.5       19.6  13.5     72.00   
435     30.7     16.0          29.6          16.0       22.9  13.6     58.90   
147     38.0     26.8          43.0          28.6       34.9  20.3     50.61   
54      31.8     13.2          31.5          13.2       21.6  13.7     65.44   
343     23.0     11.4          23.0          11.4       16.3  11.0     73.67   
48      27.7     11.3          28.0          11.3       19.2  13.7     73.76   
457     39.0     21.3          36.1          21.3       28.9   5.2     26.20   
131     37.0     24.8          36.6          24.8       30.9  15.1     39.88   
330     26.1     12.1          26.1          12.1       18.0  13.3     76.76   
368     22.5      9.7          22.5           9.7       15.8   9.2     71.11   
229     37.6     29.0          44.9          36.7       40.9  25.3     65.95   
402     25.7     10.3          25.7          10.3       17.4  11.6     72.10   
349     19.7     10.4          19.7          10.4       14.6   8.9     70.97   
73      31.7     17.0          31.4          17.0       24.3  15.4     60.61   
36      22.0      9.4          22.0           9.1       15.0  11.2     80.20   
213     32.0     27.0          44.2          31.2       36.5  27.2     91.45   
38   

In [85]:
y_train

250    29.4
280    28.9
323    19.8
271    30.1
284    28.9
291    24.7
347    15.1
22     13.2
236    32.2
68     25.1
462    32.1
154    31.0
69     25.7
418    19.2
121    32.0
407    16.0
120    34.1
483     9.2
224    32.1
176    31.4
170    29.4
361    14.2
90     27.1
159    36.8
469    32.4
178    34.5
375    11.4
297    22.3
64     22.9
0      10.1
363    11.8
192    31.7
366    12.9
419    19.6
435    23.1
147    32.2
54     21.7
343    16.3
48     19.2
457    30.3
131    31.0
330    17.9
368    15.8
229    33.0
402    17.4
349    14.6
73     24.3
36     15.0
213    28.8
38     15.6
279    28.8
83     23.4
84     24.0
140    26.1
341    16.4
184    33.0
31     16.4
481     7.1
266    28.1
285    28.0
357    15.2
200    27.8
369    13.7
289    25.0
160    34.2
61     21.4
484    11.5
344    15.5
275    30.2
158    35.5
146    32.8
182    34.0
466    32.7
464    33.4
302    22.3
115    30.1
24     12.0
14     12.9
161    31.6
438    26.9
103    31.5
408    17.4
186    34.7
474 

In [86]:
scaler = StandardScaler()

In [87]:
scaler.fit_transform(x_train)

array([[ 0.33319021,  1.14231704,  0.98569304, ..., -1.59813096,
         0.20266425,  0.63501355],
       [ 0.6573121 ,  0.8306115 ,  0.46865798, ..., -1.53299193,
        -0.96544779, -1.18072833],
       [-0.52249156, -0.33828425, -0.62394441, ...,  0.03034482,
         0.20266425,  0.63501355],
       ...,
       [ 0.78696085,  1.11634158,  0.99544842, ...,  1.56111206,
         0.20266425,  0.63501355],
       [-1.6634006 , -0.92273213, -1.48241772, ...,  0.32347046,
         1.95483231,  1.24026085],
       [ 0.37208484,  1.14231704,  0.70278706, ..., -1.10958823,
         0.20266425,  0.63501355]])

In [88]:
x_test['preciptype'] = x_test['preciptype'].map(lambda s: '<unknown>' if s not in le.classes_ else s)
le.classes_ = np.append(le.classes_, '<unknown>')

In [89]:
x_test['conditions'] = x_test['conditions'].map(lambda s: '<unknown>' if s not in le.classes_ else s)
le.classes_ = np.append(le.classes_, '<unknown>')

In [90]:
x_test['icon'] = x_test['icon'].map(lambda s: '<unknown>' if s not in le.classes_ else s)
le.classes_ = np.append(le.classes_, '<unknown>')

In [91]:
x_test['preciptype'] = le.transform(x_test['preciptype'])
x_test['conditions'] = le.transform(x_test['conditions'])
x_test['icon'] = le.transform(x_test['icon'])

In [92]:
scaler.transform(x_test)

array([[-1.22259484, -1.0396217 , -1.15073485, ...,  1.2354169 ,
         3.70700037,  0.63501355],
       [-0.52249156, -0.18243148, -0.62394441, ..., -1.63070048,
         3.70700037,  0.02976626],
       [ 0.6054526 ,  0.31110228,  0.07844284, ...,  0.87715223,
         3.70700037, -1.18072833],
       ...,
       [-1.40410309, -1.36431497, -1.28731015, ...,  0.1931924 ,
         3.70700037,  1.24026085],
       [-1.93566298, -1.70199596, -1.68728067, ...,  0.8120132 ,
         3.70700037,  0.63501355],
       [ 0.50173359, -0.52011248,  0.0979536 , ...,  0.55145707,
         3.70700037, -1.18072833]])

## Model building 

In [93]:
def predict_model(model , parameters):
    clf = GridSearchCV( model , parameters, n_jobs = -1)
    clf.fit(x_train,y_train)
    y_pred = clf.predict(x_test)
    train_score = clf.score(x_train,y_train)
    test_score = clf.score(x_test,y_test)
    best_parameters = clf.best_params_
    best_score = clf.best_score_
    
    return train_score, test_score, best_parameters

## KNN

In [94]:
knn_reg = KNeighborsRegressor()
knn_parameters = {'n_neighbors':[35,7,9,11,13], 'p':[1, 2]}

In [95]:
predict_model(knn_reg , knn_parameters)

(0.9714162794355689, 0.9528123777122413, {'n_neighbors': 7, 'p': 1})

## Linear Regression

In [96]:
lin_reg = LinearRegression()
lin_reg.fit(x_train,y_train)
y_pred = lin_reg.predict(x_test)
train_score = lin_reg.score(x_train,y_train)
test_score = lin_reg.score(x_test,y_test)



print(train_score, test_score)

0.9982216081350062 0.9368945767290758


## SVR

In [97]:
svm_reg = SVR()
svm_parameters = {'kernel':('linear', 'poly', 'rbf', 'sigmoid'), 'C':[1,10]}

In [98]:
predict_model(svm_reg ,svm_parameters)

(0.9973046111404374, 0.06612812803369483, {'C': 1, 'kernel': 'linear'})

## Saving model in pickle file

In [99]:
pickle.dump(lin_reg,open('wp.pkl','wb'))

In [100]:
model = pickle.load(open('wp.pkl','rb'))

In [101]:
model.predict([[102.1,84.1,140.9 ,95.6, 113.0, 82.9, 80.7, 0.0, 0.0, 0.0, 0 ,0.0 ,0.0 ,23.0 ,17.0 ,190.1 ,1003.5 ,32.6, 5.8, 319.1, 27.7 ,10.0, 100.0, 0.0, 2, 3]])

C:\Users\rajal\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([88.77838061])

In [102]:
model.predict([[91.3,69.8, 98.2, 69.8, 82.5, 67.3, 66.8, 0.0, 61.9, 0.0, 0, 0.0,0.0, 33.3 ,5.8, 224.7, 1009.0,67.4 ,5.0, 282.4, 24.4, 10.0, 10.0 ,0.22, 5, 4]])

C:\Users\rajal\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([77.26560518])

## Getting input from API

In [103]:
place = input('enter location')

url = f'https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/{place}?unitGroup=us&key=QFJ7RVUJAGEL2VEKBZZUB3M7H&contentType=json'


res = requests.get(url).json()
print(res)

enter locationbangalore
{'queryCost': 1, 'latitude': 12.9664, 'longitude': 77.5872, 'resolvedAddress': 'Bengaluru, KA, India', 'address': 'bangalore', 'timezone': 'Asia/Kolkata', 'tzoffset': 5.5, 'description': 'Similar temperatures continuing with a chance of rain Tuesday & Wednesday.', 'days': [{'datetime': '2022-05-27', 'datetimeEpoch': 1653589800, 'tempmax': 89.9, 'tempmin': 69.7, 'temp': 79.6, 'feelslikemax': 88.5, 'feelslikemin': 69.7, 'feelslike': 79.2, 'dew': 61.2, 'humidity': 57.2, 'precip': 0.0, 'precipprob': 81.0, 'precipcover': 0.0, 'preciptype': ['rain'], 'snow': 0.0, 'snowdepth': 0.0, 'windgust': 21.5, 'windspeed': 13.6, 'winddir': 261.3, 'pressure': 1009.5, 'cloudcover': 43.4, 'visibility': 14.1, 'solarradiation': 309.4, 'solarenergy': 26.8, 'uvindex': 10.0, 'severerisk': 10.0, 'sunrise': '05:52:35', 'sunriseEpoch': 1653610955, 'sunset': '18:41:10', 'sunsetEpoch': 1653657070, 'moonphase': 0.96, 'conditions': 'Rain, Partially cloudy', 'description': 'Partly cloudy through

In [104]:
res['days'][0]

{'datetime': '2022-05-27',
 'datetimeEpoch': 1653589800,
 'tempmax': 89.9,
 'tempmin': 69.7,
 'temp': 79.6,
 'feelslikemax': 88.5,
 'feelslikemin': 69.7,
 'feelslike': 79.2,
 'dew': 61.2,
 'humidity': 57.2,
 'precip': 0.0,
 'precipprob': 81.0,
 'precipcover': 0.0,
 'preciptype': ['rain'],
 'snow': 0.0,
 'snowdepth': 0.0,
 'windgust': 21.5,
 'windspeed': 13.6,
 'winddir': 261.3,
 'pressure': 1009.5,
 'cloudcover': 43.4,
 'visibility': 14.1,
 'solarradiation': 309.4,
 'solarenergy': 26.8,
 'uvindex': 10.0,
 'severerisk': 10.0,
 'sunrise': '05:52:35',
 'sunriseEpoch': 1653610955,
 'sunset': '18:41:10',
 'sunsetEpoch': 1653657070,
 'moonphase': 0.96,
 'conditions': 'Rain, Partially cloudy',
 'description': 'Partly cloudy throughout the day with a chance of rain.',
 'icon': 'rain',
 'stations': ['VOBL', 'remote'],
 'source': 'comb',
 'hours': [{'datetime': '00:00:00',
   'datetimeEpoch': 1653589800,
   'temp': 71.5,
   'feelslike': 71.5,
   'humidity': 94.06,
   'dew': 69.7,
   'precip': 0.

In [105]:
tempmax = res['days'][0]['tempmax']
tempmin= res['days'][0]['tempmin']
feelslikemax= res['days'][0]['feelslikemax']
feelslikemin =res['days'][0]['feelslikemin']
feelslike =res['days'][0]['feelslike']
dew =res['days'][0]['dew']
humidity =res['days'][0]['humidity']
precip =res['days'][0]['precip']
precipprob =res['days'][0]['precipprob']
precipcover =res['days'][0]['precipcover']
preciptype =res['days'][0]['preciptype']
snow =res['days'][0]['snow']
snowdepth =res['days'][0]['snowdepth']
windgust =res['days'][0]['windgust']
windspeed =res['days'][0]['windspeed']
winddir =res['days'][0]['winddir']
pressure =res['days'][0]['pressure']
cloudcover =res['days'][0]['cloudcover']
visibility =res['days'][0]['visibility']
solarradiation =res['days'][0]['solarradiation']
solarenergy =res['days'][0]['solarenergy']
uvindex =res['days'][0]['uvindex']
severerisk =res['days'][0]['severerisk']
moonphase =res['days'][0]['moonphase']
conditions =res['days'][0]['conditions']
icon =res['days'][0]['icon']


In [106]:
data = {'tempmax': tempmax,'tempmin': tempmin,'feelslikemax':feelslikemax,'feelslikemin':feelslikemin,'feelslike':feelslike,'dew':dew,'humidity':humidity,'precip':precip,'precipprob':precipprob,'precipcover':precipcover,'preciptype':preciptype,'snow':snow,'snowdepth':snowdepth,'windgust':windgust,'windspeed':windspeed,'winddir':winddir,'pressure':pressure,'cloudcover':cloudcover, 'visibility':visibility,'solarradiation':solarradiation,'solarenergy':solarenergy,'uvindex':uvindex,'severerisk':severerisk,'moonphase':moonphase,'conditions':conditions,'icon':icon}

In [107]:
df2= pd.DataFrame(data, index =[0])

In [108]:
df2

tempmax  tempmin  feelslikemax  feelslikemin  feelslike   dew  humidity  \
0     89.9     69.7          88.5          69.7       79.2  61.2      57.2   

   precip  precipprob  precipcover preciptype  snow  snowdepth  windgust  \
0     0.0        81.0          0.0       rain   0.0        0.0      21.5   

   windspeed  winddir  pressure  cloudcover  visibility  solarradiation  \
0       13.6    261.3    1009.5        43.4        14.1           309.4   

   solarenergy  uvindex  severerisk  moonphase              conditions  icon  
0         26.8     10.0        10.0       0.96  Rain, Partially cloudy  rain

In [109]:
df2['preciptype'] = df2['preciptype'].map(lambda s: '<unknown>' if s not in le.classes_ else s)
le.classes_ = np.append(le.classes_, '<unknown>')

df2['conditions'] = df2['conditions'].map(lambda s: '<unknown>' if s not in le.classes_ else s)
le.classes_ = np.append(le.classes_, '<unknown>')

df2['icon'] = df2['icon'].map(lambda s: '<unknown>' if s not in le.classes_ else s)
le.classes_ = np.append(le.classes_, '<unknown>')

In [110]:
df2['preciptype'] = le.transform(df2['preciptype'])
df2['conditions'] = le.transform(df2['conditions'])
df2['icon'] = le.transform(df2['icon'])

In [111]:
df2

tempmax  tempmin  feelslikemax  feelslikemin  feelslike   dew  humidity  \
0     89.9     69.7          88.5          69.7       79.2  61.2      57.2   

   precip  precipprob  precipcover  preciptype  snow  snowdepth  windgust  \
0     0.0        81.0          0.0           4   0.0        0.0      21.5   

   windspeed  winddir  pressure  cloudcover  visibility  solarradiation  \
0       13.6    261.3    1009.5        43.4        14.1           309.4   

   solarenergy  uvindex  severerisk  moonphase  conditions  icon  
0         26.8     10.0        10.0       0.96          11     4

In [112]:
model.predict(df2)

array([77.64253128])